app/urls.py
from django.urls import path
from . import views
from . import admin

urlpatterns = [
    path('tablo_dep/<str:lang>/', views.tablo_dep, name='tablo_dep'),
    path('tablo_arr/<str:lang>/', views.tablo_arr, name='tablo_arr'),
    path('dep/', views.departure, name='departure'),
    path('arr/', views.arrival, name='arrival'),
    path('iframe_dep/', views.iframe_dep, name='iframe_dep'),
    path('iframe_arr/', views.iframe_arr, name='iframe_arr'),
    path('deparr/', views.deparr, name='deparr'),
    path('ch/<int:pk>/', views.check_ajax, name='check_in_desk_ajax'),
    path('gate/<int:pk>/', views.gate, name='gate'),
    path('bag/<int:pk>/', views.baggage, name='baggage'),
    path('main/', views.my_urls, name='main'),
    path('get_flight_data_check/<str:lang>/<int:pk>/', views.get_flight_data_check, name='get_flight_data_check'),
    path('get_flight_data_gate/<str:lang>/G<int:pk>/', views.get_flight_data_gate, name='get_flight_data_gate'),
    path('get_flight_data_bag/<str:lang>/<int:pk>/', views.get_flight_data_bag, name='get_flight_data_bag'),
    path('generate-daily-schedule/', admin.generate_daily_schedule_view, name='generate_daily_schedule'),
    path('', views.my_urls, name='main'),
]

oss/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render
from django.urls import path


@staff_member_required
def custom_links_view(request):
    return render(request, "admin/custom_links.html")

urlpatterns = [
    path('', include('app.urls')),
    path('users/', include('users.urls')),
    path('badge/', include('IDbadge.urls')),
    path('admin/', admin.site.urls),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
import os
import datetime
from django.db import models
from django.utils.text import get_valid_filename
from django.utils import timezone
import logging
from django.core.exceptions import ValidationError

logger = logging.getLogger(__name__)

STATUS_CHOICES = (
    ('Регистрация','Регистрация'),('Посадка','Посадка'),('Отправлен','Отправлен'),(' ', ' '),
    ('По готовности','По готовности'),('Задержан','Задержан'),('Отменен','Отменен'), ('По расписанию','По расписанию'), ('Выполнен','Выполнен')
)

DIRECTION = (
    ('dep', 'Вылет'),
    ('arr', 'Прилет')
)

class Status(models.Model):
    status_id = models.CharField(max_length=2, verbose_name="ID статуса", blank=True, null=True, unique=True)
    name_ru = models.CharField(max_length=50, verbose_name="Статус на русском", blank=True, null=True, unique=True)
    name_ky = models.CharField(max_length=50, verbose_name="Статус на кыргызском", blank=True, null=True, unique=True)
    name_en = models.CharField(max_length=50, verbose_name="Статус на английском", blank=True, null=True, unique=True)

    def __str__(self):
        return "{}".format(self.name_ru)

    class Meta:
        db_table = 'Status'
        verbose_name = "Статус"
        verbose_name_plural = "Статусы"


class FlightNumber(models.Model):
    # flight_code = models.CharField(max_length=3,verbose_name="Код авиакомпании ", unique=True)
    flights = models.CharField(max_length=10,verbose_name="№ Рейса ", unique=True)
    def __str__(self):
        return "{}".format(self.flights)

    class Meta:
        db_table = 'FlightNumber'
        verbose_name = "№ Рейса"
        verbose_name_plural = "№ Рейсов"

class Cities(models.Model):
    city_name_ru = models.CharField(max_length=50, verbose_name="Город на русском")
    city_name_ky = models.CharField(max_length=50, verbose_name="Город на кыргызском")
    city_name_en = models.CharField(max_length=50, verbose_name="Город на английском")
    iata_code = models.CharField(max_length=3, verbose_name="IATA код")
    icao_code = models.CharField(max_length=4, verbose_name="ICAO код", blank=True)
    def __str__(self):
        return "{}".format(self.city_name_ru)

    class Meta:
        db_table = 'City'
        verbose_name = "Город"
        verbose_name_plural = "Города"


class Stoiki(models.Model):
    stoiki = models.CharField(max_length=2,verbose_name="Стойка № ", unique=True)
    def __str__(self):
        return "Стойка - {}".format(self.stoiki)
    def get_number(self):
        return self.stoiki

    class Meta:
        db_table = 'Stoiki'
        verbose_name = "№ Стойки"
        verbose_name_plural = "№ Стоек"

class Gates(models.Model):
    gate = models.CharField(max_length=2,verbose_name="Gate № ", unique=True)
    def __str__(self):
        return "Gate - {}".format(self.gate)
    def get_number(self):
        return self.gate

    class Meta:
        db_table = 'Gates'
        verbose_name = "Gate:"
        verbose_name_plural = "Gates:"

class Airline(models.Model):
    name = models.CharField(max_length=20, verbose_name="Авиакомпания", blank=True, unique=True)
    code = models.CharField(max_length=3, verbose_name="Код авиакомпании", blank=True, unique=True)
    logo = models.ImageField(upload_to='airline_logos/', verbose_name="Логотип", blank=True)
    svg_logo = models.FileField(upload_to='airline_logos/svg/', verbose_name="SVG логотип", blank=True)

    def save(self, *args, **kwargs):
        if Airline.objects.filter(code=self.code).exclude(pk=self.pk).exists():
            raise ValidationError(f"Авиакомпания с кодом '{self.code}' уже существует.")
        if self.svg_logo:
            # Получаем расширение файла
            svg_ext = self.svg_logo.name.split('.')[-1]
            # Создаем новое имя файла, используя поле code
            svg_new_filename = f"{self.code}.{svg_ext}"
            # Удаляем недопустимые символы из имени файла
            svg_new_filename = get_valid_filename(svg_new_filename)
            # Устанавливаем новое имя файла
            self.svg_logo.name = svg_new_filename
        
        super(Airline, self).save(*args, **kwargs)

    def __str__(self):
        return "{}".format(self.name)

    class Meta:
        db_table = 'Airline'
        verbose_name = "Авиакомпания"
        verbose_name_plural = "Авиакомпании"

from django.utils import timezone

class InfTablo(models.Model):
    direction = models.CharField(max_length=3, choices=DIRECTION)
    airline = models.ForeignKey(
        Airline,
        on_delete=models.CASCADE,
        verbose_name="Авиакомпания *",
        related_name='inftablo_airline'
    )
    flight = models.ForeignKey(
        FlightNumber,
        on_delete=models.CASCADE,
        verbose_name="Рейс № *",
    )
    destination = models.ForeignKey(
        Cities,
        on_delete=models.CASCADE,
        verbose_name="Пункт назначение *",
    )
    date1 = models.DateField("Дата плановая*", null=True)
    time1 = models.TimeField("Время плановая*", null=True)
    arr_time = models.TimeField("Время прибытия", blank=True, null=True)
    last_date = models.DateField("Дата (факт)", blank=True, null=True)
    last_time = models.TimeField("Время (факт)", blank=True, null=True)
    status = models.ForeignKey(
        Status,
        on_delete=models.CASCADE,
        verbose_name="Статус",
        blank=True,
        null=True
    )
    stoika = models.ManyToManyField(
        Stoiki,
        related_name='CheckDesk',
        verbose_name="Табло №",
        blank=True
    )
    
    gate = models.ManyToManyField(
        Gates,
        related_name='Gate',
        verbose_name="Gate:",
        blank=True
    )

    def __str__(self):
        return "{}".format(self.destination)
    
    def update_status_if_departed(self):
        """Автоматически устанавливает статус 'Отправлен' при совпадении current_time с last_time."""
        current_time = timezone.now().time()  # Текущее время
        
        # Находим статус "Отправлен" в базе данных
        sent_status = Status.objects.filter(name_ru="Отправлен").first()
          # Выводим в консоль терминала
        if sent_status:
            logger.info(f"Получен статус 'Отправлен': {sent_status}")
        else:
            logger.warning("Статус 'Отправлен' не найден в базе данных")

        # Проверяем, что поле last_time установлено и текущий статус не равен "Отправлен"
        if self.last_time and self.status != sent_status:
            # Если текущее время совпадает с last_time, устанавливаем статус "Отправлен"
            if current_time == self.last_time and sent_status:
                self.status = sent_status

    def save(self, *args, **kwargs):
        # Обновляем статус на "Отправлен", если время совпадает
        self.update_status_if_departed()
        super().save(*args, **kwargs)

    class Meta:
        db_table = "InfTablo"
        verbose_name = '"Суточный план"'
        verbose_name_plural = "Суточный план"

class FlightForTemplate(models.Model):
    airline = models.ForeignKey(
        Airline,
        on_delete=models.CASCADE,
        verbose_name="Авиакомпания *",
        related_name='template_airline',
        default=1
    )
    flight = models.ForeignKey(
        FlightNumber,
        on_delete=models.CASCADE,
        verbose_name="Рейс № *",
        related_name='template_flight',
        default=1
    )
    destination = models.ForeignKey(
        Cities,
        on_delete=models.CASCADE,
        verbose_name="Пункт назначение *",
        related_name='template_destination',
        default=1
    )
    
    

    def __str__(self):
        return "{}".format(self.flight)

    class Meta:
        verbose_name = "Информация о рейсе"
        verbose_name_plural = "Информации о рейсах"

class FlightTemplate(models.Model):
    """
    Модель для хранения шаблонов рейсов.
    """
    direction = models.CharField("Направление *", max_length=10, default="", choices=DIRECTION)
    season_start = models.DateField("Начало сезона")
    season_end = models.DateField("Конец сезона")
    weekdays = models.CharField(
        "Дни вылета", 
        max_length=20, 
        help_text="Введите дни недели через запятую, например: 1,3,5 для понедельника, среды и пятницы"
    )
    period_start = models.DateField("Начало периода рейса")
    period_end = models.DateField("Конец периода рейса")
    time = models.TimeField("Время плановая*", null=True)

    flight = models.ForeignKey(
        FlightForTemplate,  # Связываем с моделью InfTablo
        on_delete=models.CASCADE,  # Удаление рейса приведёт к удалению всех шаблонов
        verbose_name="Рейс", 
        related_name="flight_templates"  # Обратная связь: InfTablo.flight_templates.all()
    )


    def __str__(self):
        return f"Шаблон рейса {self.flight.flight} ({self.season_start} - {self.season_end})"

    class Meta:
        verbose_name = "Шаблон рейса"
        verbose_name_plural = "Шаблоны рейсов"

app/templates/app/aeroflot.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ввод Значения</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
            background-color: #f4f4f9;
        }
        input[type="text"] {
            width: 300px; /* Ширина поля ввода */
            padding: 10px; /* Отступы внутри поля */
            font-size: 16px; /* Размер шрифта */
            margin-bottom: 20px; /* Отступ снизу */
            border: 1px solid #ccc; /* Цвет рамки */
            border-radius: 5px; /* Закругление углов */
        }
        button {
            padding: 10px 20px; /* Отступы внутри кнопки */
            font-size: 16px; /* Размер шрифта */
            background-color: #007bff; /* Цвет фона кнопки */
            color: white; /* Цвет текста */
            border: none; /* Убираем рамку */
            border-radius: 5px; /* Закругление углов */
            cursor: pointer; /* Указатель при наведении */
        }
        button:hover {
            background-color: #0056b3; /* Цвет фона при наведении */
        }
    </style>
</head>
<body>
    <h2>Введите значение</h2>
    <input type="text" id="user-input" placeholder="Введите значение">
    <input type="text" id="user-input-2" placeholder="Введите второе значение"> <!-- Новое поле ввода -->
    <button onclick="submitValue()">Отправить</button>

    <script>
        function submitValue() {
            const input = document.getElementById("user-input").value;
            const input2 = document.getElementById("user-input-2").value; // Второе значение
    
            if (input.trim()) {
                // Сохраняем значения в sessionStorage
                sessionStorage.setItem("displayValue", input);
                sessionStorage.setItem("displayValue2", input2);
                // Переходим на страницу вывода
                window.location.href = "display.html";
            }
        }
    </script>
    
</body>
</html>

app/templates/app/baggage_ajax.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/baggage.css' %}" rel="stylesheet">
    <title>Baggage {{pk}}</title>
</head>
<body>
    
    <div id="content" class="container"></div>
    <div class="checkin-number">{{ pk }}</div>

    <script>
        const advertImageURL = "{% static 'images/advertisement/advert.png' %}";
    </script>
    <script src="{% static 'js/baggage.js' %}"></script>
</body>
</html>

app/templates/app/base copy.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}OSS Суточный план{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/js/bootstrap.js' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header>
        <img src="{% static 'images/logomanas.svg' %}" alt="Логотип" class="logoosh">
        <!-- <h2>{% block page_header %}Default Page Header{% endblock %}</h2> -->
        {% if user.is_authenticated %}
        <div class="navigation">
                    <a href="{% url 'logout' %}" class="button">
                        
                            <img src="{% static 'images/user.svg' %}" alt="user" class="user-icon">
                            <div class="logout "><img src="{% static 'images/logout.svg' %}" alt="sign-out" class="sign-out-icon"></div>
                    </a>
                    {% else %}
                    <a href="{% url 'login' %}" class="button">
                        
                        <img src="{% static 'images/user.svg' %}" alt="user" class="user-icon">
                        <div class="logout "><img src="{% static 'images/login.svg' %}" alt="sign-in" class="sign-in-icon"></div>
                    </a>
            </div>
        </div>
            {% endif %}
        
    </header>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div class="message {{ message.tags }}">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}

    <main class="content">
        {% block content %}{% endblock %}
    </main>

    <footer>
        <p>&copy; 2024 Eldyear</p>
    </footer>
</body>
</html>

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}OSS Суточный план{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles copy.css' %}">
</head>
<body>
    <header>
        <a href="{% url 'user_menu' %}"><img src="{% static 'images/logomanas.svg' %}" alt="Логотип" class="logoosh"></a>
        <h2>{% block page_header %}Default Page Header{% endblock %}</h2>
                {% if user.is_authenticated %}
                <div class="navigation">
                            <a href="{% url 'logout' %}" class="button">
                                
                                <img src="{% static 'images/user.svg' %}" alt="user" class="user-icon">
                                <div class="logout "><img src="{% static 'images/logout.svg' %}" alt="sign-out" class="sign-out-icon"></div>
                            </a>
                            {% else %}
                            <a href="{% url 'login' %}" class="button">
                                
                                <img src="{% static 'images/user.svg' %}" alt="user" class="user-icon">
                                <div class="logout "><img src="{% static 'images/login.svg' %}" alt="sign-in" class="sign-in-icon"></div>
                            </a>
                    </div>
                </div>
                {% endif %}
        
    </header>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div class="message {{ message.tags }}">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}

    <main class="content">
        {% block content %}{% endblock %}
    </main>

    <footer>
        <p>&copy; 2024 Eldyear</p>
    </footer>
</body>
</html>

app/templates/app/check_ajax.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/check.css' %}" rel="stylesheet">
    <title>Check-in {{pk}}</title>
</head>
<body>
    
    <div id="content" class="container"></div>
    <div class="checkin-number">{{ pk }}</div>

    <script>
        const advertImageURL = "{% static 'images/advertisement/advert.png' %}";
    </script>
    <script src="{% static 'js/check_in.js' %}"></script>
</body>
</html>

app/templates/app/deparr.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flight Information</title>
    <style>
        body {
            margin: 0;
            overflow: hidden;
        }
        .iframe-container {
            display: flex;
            overflow: hidden;
        }
        .iframe-section {
            width: 50vw; /* Установим ширину для равномерного размещения */
            height: 100vh; /* Устанавливаем высоту для полноэкранного отображения */
            border: none; 
            overflow: hidden;
        }
    </style>
</head>
<body>
    <div class="iframe-container">
        <!-- Замените URL ниже на нужные страницы -->
        <iframe src="/iframe_dep"  class="iframe-section" title="Вылеты"></iframe>
        <iframe src="/iframe_arr/" class="iframe-section" title="Прилеты"></iframe>
    </div>
</body>
</html>

app/templates/app/departure_ajax.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Departure OSS</title>
    <link rel="stylesheet" href="{% static 'css/deparstyle.css' %}">
</head>
<body>
    <div id="table-container"></div> <!-- Контейнер для таблиц -->
    <div id="static-data" data-depart-plane="{% static 'images/departplane.png' %}"></div>
    
    <script src="{% static 'js/dep.js' %}"></script> <!-- Скрипт с логикой -->
</body>
</html>

app/templates/app/flight_template_list.html
{% extends "base.html" %}

{% block title %}Шаблоны суточного плана{% endblock %}

{% block page_header %}Шаблоны суточного плана{% endblock %}

{% block content %}

<!-- Кнопка для добавления нового шаблона -->
<div class="flight-template-add">
    <a href="{% url 'flight_template_add' %}" class="btn btn-success">Добавить новый шаблон</a>
</div>

<!-- Таблица с шаблонами -->
<table class="table">
    <thead>
        <tr>
            <th>Направление</th>
            <th>Рейс</th>
            <th>Сезон</th>
            <th>Дни вылета</th>
            <th>Время</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        {% for template in flight_templates %}
        <tr>
            <td>{{ template.get_direction_display }}</td>
            <td>{{ template.flight }}</td>
            <td>{{ template.season_start }} - {{ template.season_end }}</td>
            <td>{{ template.weekdays }}</td>
            <td>{{ template.time }}</td>
            <td class="row action-td">
                <form action="{% url 'flight_template_delete' template.pk %}" method="post" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger"></button>
                </form>
                <a href="{% url 'flight_template_edit' template.pk %}" class="btn-edit"></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- Пагинация -->
<div class="pagination">
    <span class="step-links">
        {% if flight_templates.has_previous %}
            <a href="?page=1">&laquo; первая</a>
            <a href="?page={{ flight_templates.previous_page_number }}"><</a>
        {% endif %}

        <span class="current">
            Страница {{ flight_templates.number }} из {{ flight_templates.paginator.num_pages }}
        </span>

        {% if flight_templates.has_next %}
            <a href="?page={{ flight_templates.next_page_number }}">></a>
            <a href="?page={{ flight_templates.paginator.num_pages }}">последняя &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

app/templates/app/gate.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/check.css' %}" rel="stylesheet">
    <title>Gate {{pk}}</title>
</head>
<body>
    
    <div id="content" class="container"></div>
    <div class="checkin-number">G{{ pk }}</div>

    <script>
        const advertImageURL = "{% static 'images/advertisement/advert.png' %}";
    </script>
    <script src="{% static 'js/gate.js' %}"></script>
</body>
</html>

app/templates/app/my_urls.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

<div class="links">
    <!-- <h3>Аэропорт Ош</h3> -->
    <img src="{% static 'images/logobadge.svg' %}" alt="Логотип Ош" class="logo"/>
    <div>
        <div class="dep">
            <div><a href="/users/login/" class="button-link" target="_blank">Авторизация</a></div>
            <div><a href="/users/flight-templates/" class="button-link" target="_blank">Формирование Шаблона</a></div>
        </div>
        <div class="dep">
            <div><a href="/dep/" class="button-link" target="_blank">Табло ВЫЛЕТОВ</a></div>
            <div><a href="/arr/" class="button-link" target="_blank">Табло ПРИЛЕТОВ</a></div>
        </div>
        <div>
            <input type="text" id="pkInput" placeholder="Введите ID">
            <a href="#" onclick="redirectToUrl()" class="button-link" target="_blank">Табло регистрации</a>
        </div>
        <div>
            <input type="text" id="pkInputGate" placeholder="Введите ID">
            <a href="#" onclick="redirectToGateUrl()" class="button-link" target="_blank">Табло выхода (гейт)</a>
        </div>
        <div>
            <input type="text" id="pkInputBaggage" placeholder="Введите ID">
            <a href="#" onclick="redirectToBaggageUrl()" class="button-link" target="_blank">Табло выдачи багажа</a>
        </div>
    </div>
</div>

<script>
    function redirectToUrl() {
        const pk = document.getElementById('pkInput').value;  // Получаем значение из input
        if (pk) {
            const url = `/ch/${pk}`;  // URL для табло регистрации с ID
            window.open(url, '_blank');  // Открывает ссылку в новой вкладке
        } else {
            alert("Пожалуйста, введите ID.");  // Сообщение об ошибке, если поле пустое
        }
    }

    function redirectToGateUrl() {
        const pk = document.getElementById('pkInputGate').value;  // Получаем значение из input для выдачи багажа
        if (pk) {
            const url = `/gate/${pk}`;  // URL для табло выдачи багажа с ID
            window.open(url, '_blank');  // Открывает ссылку в новой вкладке
        } else {
            alert("Пожалуйста, введите ID.");  // Сообщение об ошибке, если поле пустое
        }
    }
    function redirectToBaggageUrl() {
        const pk = document.getElementById('pkInputBaggage').value;  // Получаем значение из input для выдачи багажа
        if (pk) {
            const url = `/bag/${pk}`;  // URL для табло выдачи багажа с ID
            window.open(url, '_blank');  // Открывает ссылку в новой вкладке
        } else {
            alert("Пожалуйста, введите ID.");  // Сообщение об ошибке, если поле пустое
        }
    }
</script>

app/templates/app/user_menu.html
<!-- templates/inftablo_form.html -->
{% extends "base.html" %}

{% block page_header %}Меню{% endblock %}

{% block content %}

<div class="menu">
    <a href="{% url 'inftablo_list' %}" class="btn btn-success menu-btn">Суточный план</a>
    <a href="{% url 'flight_template_list' %}" class="btn btn-success menu-btn">Шаблон Суточный план</a>
    <a href="{% url 'generate_daily_schedule' %}" class="btn btn-success menu-btn">Формирование суточного плана</a>
</div>

{% endblock %}